import Converter from "./converter.interfaces";

const SELF_TYPE = "mousebase.TfmEvents";

const eventEnumConverter = {
  name: "eventEnum.lua",
  convert: (luaHelpAst) => {
    const lines = [
      "--- @meta",
      "-- !! This file is generated by an NPM script. !!",
      "",
    ];

    lines.push(`--- @alias ${SELF_TYPE}.Events`);

    for (const e of luaHelpAst.events) {
      const m = e.name.match(/^event(\w+)$/);
      if (!m) throw new Error("Unexpected event name: " + e.name);

      lines.push(
        `---| '"${m[1]}"'${e.description[0] ? " # " + e.description[0] : ""}`
      );
    }

    return lines;
  },
} as Converter;
export default eventEnumConverter;
